apiVersion: apps/v1
kind: Deployment
metadata:
  name: pywebapp
  labels:
    app: pywebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pywebapp
  template:
    metadata:
      labels:
        app: pywebapp
    spec:
      containers:
      - name: pywebapp
        image: nginx:latest
        ports:
        - containerPort: 8080
